# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=random
spring.security.oauth2.client.registration.google.client-secret=random
spring.security.oauth2.client.registration.google.scope=email,profile
# Github OAuth 2.0
spring.security.oauth2.client.registration.github.client-id=random
spring.security.oauth2.client.registration.github.client-secret=random
spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
cloudinary.api.key=random
cloudinary.api.secret=random
cloudinary.cloud.name=random
#Email configurations
spring.mail.host=random
spring.mail.port=200
spring.mail.username=random
spring.mail.password=random
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.domain_name=random